### ISSUE TITLE
unix_dgram doesn't seem to be optional

### ISSUE THREAD

**Issue by augustblack** [meetecho/janode#10]
I might be doing something wrong, but on a very basic install on linux, `npm install` will work, but then I get a runtime error:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'unix-dgram' imported from node_modules/janode/src/transport-unix.js`

I'm only using the websocket connection.

**Comment by atoppi** [comment]
Can you please provide some steps to reproduce ? 
This is really unexpected, we use `janode` installed from npm in many projects.

**Comment by atoppi** [comment]
is this still an issue ?
