### ISSUE TITLE
Provide NPM package

### ISSUE THREAD

**Issue by capital-G** [meetecho/janode#21]
As this is the standard JS interface library for janus (is it? it seems so from https://github.com/meetecho/janus-gateway/issues/2960 but it does not support everything, see https://github.com/meetecho/janode/issues/19) I don't understand why it is not on npm? Isn't one of the major applications of janus to use it in a web environment/browser? So how should one use this library in a project - copy the source code or use git-submodules? both seems no good choices if there exists an package manager for node which solves these problems.

**Comment by lminiero** [comment]
> I don't understand why it is not on npm?

It is: https://www.npmjs.com/package/janode

**Comment by capital-G** [comment]
Oh cool, sorry :) Maybe add a link to it on the `README.md`? :)

**Comment by atoppi** [comment]
> Oh cool, sorry :) Maybe add a link to it on the `README.md`? :)

Thanks for the feedback, I've just pushed the change in https://github.com/meetecho/janode/commit/a8a4b946de63aa5fa8fbd8e20c2b9041ee2c9e7d.

> So how should one use this library in a project - copy the source code or use git-submodules? both seems no good choices if there exists an package manager for node which solves these problems.

Side note: you can add dependencies in your `package.json` by referring them by git url.
E.g. in case you want to test your application against janode master:

`package.json`
```json
  "dependencies": {
    "express": "^4.17.1",
    "janode": "git+https://github.com/meetecho/janode.git",
    "socket.io": "^4.2.0"
  },
```
