### ISSUE TITLE
date channel

### ISSUE THREAD

**Issue by marconildo** [meetecho/janode#25]
I currently use Janus as a webrtc server and I have a video feed and a metadata feed associated with the video feed. using this new approach how would it work? I will receive everything via WS or would it have to be a different port. or is it not supported? thanks

**Comment by atoppi** [comment]
janode is a signalling library for the Janus API and does not directly handle data channels or other media, it just helps establish and negotiate connections.
Please refer to the[ official community](https://janus.discourse.group/c/janode/8) for other questions like this.
