### ISSUE TITLE
wss test

### ISSUE THREAD

**Issue by interfaith** [meetecho/janode#26]
https://teleden.com:8081 is ok via wss://teleden.com via nginx

here i get
[ERR_MODULE_NOT_FOUND]: Cannot find package 'isomorphic-ws' imported from /home/spowage/janode/src/transport-ws.js
with

export default {
  janode: {
    address: [{
      url: 'wss://teleden.com/',
      apisecret: 'secret'
    }],
    // seconds between retries after a connection setup error
    retry_time_secs: 10
  },
  web: {
    port: 4443,
    bind: '0.0.0.0',
    key: '/etc/letsencrypt/live/teleden.com/cert.pem',
    cert: '/etc/letsencrypt/live/teleden.com/privkey.pem'
  }
};
spowage@teleden:~/janode/examples/videoroom/src$

**Comment by interfaith** [comment]
require instead of import seems to fix it

**Comment by interfaith** [comment]
maybe the node version must be set ?

**Comment by atoppi** [comment]
I have no idea sorry, please submit questions like this in the [discussion group](https://janus.discourse.group/c/janode).

We set this node versions in the package.json
```
  "engines": {
    "node": " >=14.13.1 || >=16.0.0"
  },
```
