### ISSUE TITLE
Speakerphone can not be selected on iOS

### ISSUE THREAD

**Issue by cityrolr** [meetecho/janode#31]
Hello 👋
While attending the IETF meeting over the past few days, I have been using the mobile client via Safari on iOS 17.1.1 quite a bit. However, I noticed that the audio is not coming through the speakerphone (not sure if that is the right term, but I just mean the speaker that plays music etc.). Instead, the audio comes through the earpiece (the one we used for phone calls when AirPods didn't exist), which is much louder.

I am not entirely sure if this is exactly the case because I also feel like there is sound coming from both speakers, but in general the volume is about 50% lower than any other audio I can play on my iOS device.

**Comment by lminiero** [comment]
Hey @cityrolr! While we do use Janode as part of the Meetecho IETF participation service, it's only used on the server side, and not the client side, so the issue you mentioned doesn't apply to this project, which uses a different client stack. That said, it is an issue we're already aware of (we replicated a behaviour similar to the one you described), and so are tracking already. In case you want to notify other issues in the future, please send the related info to support@ietf.org.

Thanks!
