### ISSUE TITLE
Leave and unpublish event not work for v1.3.0

### ISSUE THREAD

**Issue by mDev86** [meetecho/janode#49]
After update janus version to 1.3.0, `leave` and `unpublish` events stopped being called in videoroom.
Probably caused by https://github.com/meetecho/janus-gateway/pull/3426. `leave` or `unpublish` not reached because `display` now is not undefined

<img width="899" alt="изображение" src="https://github.com/user-attachments/assets/c41079f0-818b-4aba-96da-eaf820d45e19">

**Comment by atoppi** [comment]
Nice catch!
Can you try by moving the `DISPLAY` event parsing block after the `LEAVING` ?

**Comment by atoppi** [comment]
Thanks!
Fixed by #50.
