### ISSUE TITLE
audiobridge feed/id on join is weird

### ISSUE THREAD

**Issue by augustblack** [meetecho/janode#7]
This is a two-part issue report.

First, the naming of 'id' to 'feed' on audiobridge join is a bit weird.  Since it doesn't match the janus backend name of 'id', any error reports for it will be misleading.

Second, if you have your audiobridge set with `string_ids = "true";`  and you don't pass in the 'feed' var on join, you will get an error.

Potential fix might be to simply allow 'feed' on join to be number|string and then NOT set a default value of `feed =. 0`

Ideally, I think "feed" should be "id" to match the janus backend (but, I imagine there was a reason to rename it)

**Comment by atoppi** [comment]
The above commit should fix the errors when using string ids for both audiobridge and videoroom.
As suggested the default is not set and string/number ids are fully supported when joining and creating.

> Ideally, I think "feed" should be "id" to match the janus backend (but, I imagine there was a reason to rename it)

Indeed there is. The Janus API for audiobridge and videoroom often refers to the same value (the participant `id`) with different names, depending on the request/event. I was trying to streamline that ambiguous naming, by using a new name (`feed`) and sticking to it anywhere.

Please check if the commit fixes the issue for you.

**Comment by augustblack** [comment]
yup, that seems to work now.  thanks
