### ISSUE TITLE
audiobridge join does not seem to return AUDIOBRIDGE_EVENT_JOINED

### ISSUE THREAD

**Issue by augustblack** [meetecho/janode#8]
when I do audioHandle.join(...)

I get Promise<{ feed, room, participants }> in return. 

This matches janus except that it seems to return without the 'display' field.

However, the docs seem to indicate it should return Promise<AUDIOBRIDGE_EVENT_JOINED>

Maybe just a documentation error?

**Comment by atoppi** [comment]
That is a documentation error.
`AUDIOBRIDGE_EVENT_JOINED` is not correctly defined.

**Comment by atoppi** [comment]
I've double-checked how those events are emitted from Janus, fixed the payloads and the documentation accordingly.
The commit is https://github.com/meetecho/janode/commit/d82f0c068ded9830188ebe7e2a3fef8fe0f36b59.

Please verify that everything works as expected.

**Comment by augustblack** [comment]
looks good!  

The 'display' is still not being returned on the join request.

Is that maybe a janus issue?

**Comment by atoppi** [comment]
The Janus doc mentions the `display` in the joined event, but the actual code does not insert that field in the json.
I could add the `display` by returning the one passed by the user.

**Comment by atoppi** [comment]
Closing the issue since the original problem has been solved.
Please open a new issue for other questions.
